# Shapes
SHAPE_NULL = 0
SHAPE_SPHERE = 1
SHAPE_CYLINDER = 2
SHAPE_ANNULUS = 3

# Hittables
HITTABLE_NULL = 0
HITTABLE_BLACKBODY = 1
HITTABLE_CHECKERBOARD = 2

# Gravitational Fields
GRAVFIELD_MINKOWSKI = 0
GRAVFIELD_SCHWARZSCHILD = 1
GRAVFIELD_KERR = 2
GRAVFIELD_KERRNEWMAN = 3

# Integrators
INTEGRATOR_GEODESICEQ = 0
INTEGRATOR_SPECINT = 1