# Shapes
SHAPE_NULL = 0
SHAPE_SPHERE = 1
SHAPE_CYLINDER = 2
SHAPE_ANNULUS = 3

# Hittables
HITTABLE_NULL = 0
HITTABLE_LIGHT = 1

# Color Fields
COLFIELD_CONSTCOL = 0
COLFIELD_CHECKERBOARD = 1

# Gravitational Fields
GRAVFIELD_MINKOWSKI = 0
GRAVFIELD_SCHWARZSCHILD = 1
GRAVFIELD_KERR = 2
GRAVFIELD_KERRNEWMAN = 3